apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
      matchLabels:
          app: myapp
  replicas: 4
  template:
    metadata:
      labels:
          app: myapp
    spec:
      containers:
      - name: testpage
        image: # image container url created in Azure or other Cloud platform
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: webapp